# Site settings
title: "Laura Salinas"
email: laurabug2010@gmail.com
description: "A blog about a teacher turned frontend engineer"
baseurl: ""
url: http://laurabug.github.io/
#url: http://localhost:4000
title_description: "A blog about a teacher turned frontend engineer"
title_image: images/laura.jpg
github_repository: https://github.com/laurabug/laurabug.github.io
addthis_id: ra-55ce1c12be735db0
post_limit: 15

# Social usernames/URLs
github_username:  laurabug
linkedin_link: https://www.linkedin.com/in/laurasalinas1
google_plus_link: http://google.com/+LauraSalinas1 

# Footer
footer_left: "Created by <a href=\"https:ttps://www.linkedin.com/in/laurasalinas1\">Laura Salinas</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/laurabug/laurabug.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
